baseURL = "https://piesp.github.io/"
languageCode = "ko"
title = "PiesP의 블로그"
theme = "PaperMod"
defaultContentLanguage = "ko"
enableRobotsTXT = true
publishDir = "public"

paginate = 10

[outputs]
  home = ["HTML", "RSS", "JSON", "sitemap"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  author = "PiesP"
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  
  # SEO 설정
  description = "PiesP의 개인 블로그입니다"
  keywords = ["blog", "hugo", "PiesP"]

  # 소셜 링크 설정
  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/PiesP"
  
  [[params.socialIcons]]
  name = "YouTube"
  url = "https://www.youtube.com/@piesp"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    name = "Videos"
    url = "/videos/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5
