baseURL = "https://piesp.github.io/"
languageCode = "ko"
title = "PiesP의 블로그"
theme = "PaperMod"
defaultContentLanguage = "ko"
enableRobotsTXT = true
publishDir = "public"

paginate = 10  # 페이지당 포스트 수

relativeURLs = false
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON", "sitemap", "robots"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  author = "PiesP"
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  
  # SEO 설정
  description = "PiesP의 개인 블로그입니다"
  keywords = ["blog", "hugo", "PiesP"]
  
  # 소셜 미디어 공유 설정
  [params.socialIcons]
    # GitHub 아이콘 예시 (필요에 따라 수정하세요)
    [[params.socialIcons]]
      name = "Github"
      url = "https://github.com/PiesP"
    
    # 다른 플랫폼도 추가할 수 있습니다 (Twitter, Facebook 등)

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
    
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

# Module imports are not needed when using submodule
