baseURL = "https://piesp.github.io/"
languageCode = "ko"
title = "PiesP의 블로그"
theme = "PaperMod"
defaultContentLanguage = "ko"
enableRobotsTXT = true
publishDir = "public"

[pagination]
  pagerSize = 10  # 기존 paginate 제거 후 최신 설정 적용

relativeURLs = false
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "sitemap", "robots"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  author = "PiesP"
  defaultTheme = "auto"
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[module]
  [[module.imports]]
    path = "PaperMod"
