baseURL = "https://piesp.github.io/"
languageCode = "ko"
title = "PiesP의 블로그"
theme = "PaperMod"
defaultContentLanguage = "ko"
enableRobotsTXT = true
publishDir = "public"

[pagination]
  pagerSize = 10

relativeURLs = true
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[module]
  [[module.imports]]
    path = "PaperMod"
