baseURL = "https://piesp.github.io/"
languageCode = "en-us"
title = "PiesP's Page"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"