name: Update videos posts

on:
  schedule:
    - cron: '0 15 * * *'  # Run workflow every day at 15:00 UTC (which is 0:00 JST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.JEKYLL_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check directory state before
      run: ls _posts > /tmp/before.txt

    - name: Update videos
      run: python scripts/update_videos.py --template_path "scripts/post.template"
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    - name: Check directory state after
      run: ls _posts > /tmp/after.txt

    - name: Push changes
      run: |
        if ! diff /tmp/before.txt /tmp/after.txt; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _posts
          git commit -m "Update videos posts"
          git push
        fi

    - name: Trigger deploy workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: deploy-jekyll
  
